version: 2

registries:
  nyastack:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_PACKAGES_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
      exclude:
        - "@nayaccr/*"
    registries:
      - nyastack
    allow:
      - dependency-name: "@nayaccr/*"
    groups:
      nyastack:
        patterns:
          - "@nayaccr/*"
