"use client";

import { useRef, useState } from "react";
import { Check, Database, Download, ExternalLink, Link2, RotateCcw, Settings, Shield, Upload } from "lucide-react";
import { useAppData } from "@/components/providers/app-data-provider";
import { PageHeader, SectionTitle, buttonSecondary, inputClass } from "@/components/ui/app-ui";
import { defaultProfiles, defaultProviders, defaultSettings, normalizeOptions } from "@/lib/app-data";

export default function SettingsPage() {
  const { providers, profiles, history, settings, setProviders, setProfiles, setHistory, setSettings } = useAppData();
  const [saved, setSaved] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  function change<K extends keyof typeof settings>(key: K, value: typeof settings[K]) { setSettings((current) => ({ ...current, [key]: value })); setSaved(true); window.setTimeout(() => setSaved(false), 1200); }
  function exportData() { const blob = new Blob([JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), providers, profiles, history, settings }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `nyasub-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); }
  async function importData(file?: File) { if (!file) return; try { const data = JSON.parse(await file.text()); if (Array.isArray(data.providers)) setProviders(data.providers); if (Array.isArray(data.profiles)) setProfiles(data.profiles.map((profile: typeof defaultProfiles[number]) => ({ ...profile, ...normalizeOptions(profile) }))); if (Array.isArray(data.history)) setHistory(data.history); if (data.settings) setSettings({ ...defaultSettings, ...data.settings }); alert("数据导入完成"); } catch { alert("无法读取此备份文件"); } }
  return <div className="mx-auto w-full max-w-4xl space-y-6 px-4 py-7 sm:px-6 lg:py-9"><PageHeader title="设置" description="管理公共服务列表、本地隐私偏好和数据备份。更改会自动保存在当前浏览器。" action={saved ? <span className="inline-flex items-center gap-1.5 text-xs text-emerald-600 dark:text-emerald-400"><Check className="h-4 w-4" />已保存</span> : undefined} />
    <section className="space-y-5 rounded-lg border border-border bg-card p-5 sm:p-6"><SectionTitle icon={Settings} title="公共服务列表" description="填写返回 Provider 数组的 JSON 地址，可在转换后端页面手动更新" /><label className="block space-y-2 text-sm font-medium"><span>远程列表 URL</span><input value={settings.publicListUrl} onChange={(e) => change("publicListUrl", e.target.value)} placeholder="https://example.com/providers.json" className={inputClass} /><span className="block text-[11px] font-normal leading-5 text-muted-foreground">支持数组或 <code className="rounded bg-muted px-1">{"{ providers: [...] }"}</code>，远程项至少包含 name 与 endpoint。</span></label></section>
    <section className="space-y-5 rounded-lg border border-border bg-card p-5 sm:p-6"><SectionTitle icon={Link2} title="扩展服务" description="短链和配置托管不是 SubConverter 标准接口，按需接入你信任的服务" /><div className="grid gap-4"><ServiceField label="默认短链 API" value={settings.shortUrlEndpoint} placeholder="https://example.com/short" hint="兼容 sub-web-api：接收 longUrl、可选 shortKey，返回 ShortUrl。" onChange={(value) => change("shortUrlEndpoint", value)} /><ServiceField label="远程配置托管 API" value={settings.configUploadEndpoint} placeholder="https://example.com/sub.php" hint="接收 config 表单字段，返回 { code: 0, data: URL }。" onChange={(value) => change("configUploadEndpoint", value)} /><ServiceField label="脚本处理 API（预留）" value={settings.scriptApiEndpoint} placeholder="https://example.com/api.php" hint="参考项目的 JS 排序/筛选功能目前已暂停，此处只保留自建服务地址。" onChange={(value) => change("scriptApiEndpoint", value)} /></div><div className="rounded-md border border-amber-500/25 bg-amber-500/8 p-3 text-xs leading-5 text-muted-foreground">短链服务会收到完整转换链接，配置托管服务会收到配置正文。地址默认留空，NyaSub 不会自动调用任何公共扩展服务。</div></section>
    <section className="space-y-2 rounded-lg border border-border bg-card p-5 sm:p-6"><SectionTitle icon={Shield} title="隐私与转换" description="这些设置只影响当前浏览器" /><SettingToggle title="保存订阅来源" description="在历史记录中保留原始订阅地址，关闭后仅保存链接数量" checked={settings.rememberSource} onChange={(value) => change("rememberSource", value)} /><SettingToggle title="界面隐藏敏感链接" description="使用掩码显示生成链接与历史来源，复制和打开仍使用完整地址" checked={settings.maskSource} onChange={(value) => change("maskSource", value)} /><SettingToggle title="转换前检查后端" description="保留用于需要严格可用性检查的部署策略" checked={settings.checkBeforeConvert} onChange={(value) => change("checkBeforeConvert", value)} /></section>
    <section className="space-y-5 rounded-lg border border-border bg-card p-5 sm:p-6"><SectionTitle icon={Database} title="本地数据" description={`${providers.length} 个后端 · ${profiles.length} 个 Profile · ${history.length} 条历史`} /><div className="flex flex-wrap gap-2"><button type="button" onClick={exportData} className={buttonSecondary}><Download className="h-4 w-4" />导出备份</button><button type="button" onClick={() => inputRef.current?.click()} className={buttonSecondary}><Upload className="h-4 w-4" />导入备份</button><input ref={inputRef} type="file" accept="application/json" className="hidden" onChange={(e) => importData(e.target.files?.[0])} /><button type="button" onClick={() => { if (window.confirm("这会清除所有自定义数据并恢复初始状态，确定继续吗？")) { setProviders(defaultProviders); setProfiles(defaultProfiles); setHistory([]); setSettings(defaultSettings); } }} className={buttonSecondary}><RotateCcw className="h-4 w-4" />恢复默认</button></div></section>
    <section className="flex flex-col gap-4 rounded-lg border border-border bg-muted/30 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold">NyaSubConverter</h2><p className="mt-1 text-xs text-muted-foreground">独立的开源订阅转换 Web Client</p></div><a href="https://github.com/tindy2013/subconverter" target="_blank" rel="noreferrer" className={buttonSecondary}><ExternalLink className="h-4 w-4" />SubConverter 项目</a></section>
  </div>;
}

function SettingToggle({ title, description, checked, onChange }: { title: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4 border-t border-border py-4 first:border-0"><span><span className="block text-sm font-medium">{title}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{description}</span></span><button type="button" role="switch" aria-label={title} aria-checked={checked} onClick={() => onChange(!checked)} className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${checked ? "bg-primary" : "bg-muted-foreground/30"}`}><span className={`absolute left-1 top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${checked ? "translate-x-5" : "translate-x-0"}`} /></button></div>; }

function ServiceField({ label, value, placeholder, hint, onChange }: { label: string; value: string; placeholder: string; hint: string; onChange: (value: string) => void }) { return <label className="space-y-2 text-sm font-medium"><span>{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className={inputClass} /><span className="block text-[11px] font-normal leading-5 text-muted-foreground">{hint}</span></label>; }
